name: Build and Deploy to VM

on:
  push:
    branches:
      - feature/gitworkflow

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '19.0.1'

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $VM_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_IP: ${{ secrets.VM_IP }}

      - name: Access VM and Check Nginx Status
        run: |
          ssh $VM_USERNAME@$VM_IP
          pwd
          sudo systemctl status nginx
          cd /home/githubactionuser/banana-admin
          ls
          git pull origin feature/gitworkflow
          npm run build
          sudo systemctl restart nginx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_IP: ${{ secrets.VM_IP }}
          VM_USERNAME: ${{ secrets.VM_USERNAME }}

      - name: Clean up SSH key
        run: |
          rm -f ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}